### ISSUE TITLE
Option for incremental building

### ISSUE THREAD

**Issue by galvanopus** [excelsior-oss/excelsior-jet-maven-plugin#14]
Such option can significantly decrease compilation time.

**Comment by pjBooms** [comment]
We have implemented incremental builds in 64-bit versions of Excelsior JET 15. You may find beta version here -  https://www.excelsiorjet.com/beta . Please download it and give us feedback if it works for you. 

Incremental build should work in current versions of the plugin for 64-bit JET 15 until you do clean build. No option is actually required as incremental build is default behaviour of JET compiler starting with JET 15 . 

In the next version of the plugin we are going to store project database (compilation cache) 
outside of Maven build directory (presumably at $(user.home)/.ExcelsiorJET) so even for the clean build the project dependencies will not be re-compiled (you'll be able to switch off the option of course).

**Comment by galvanopus** [comment]
It's better to say "Thank you" later than never. Thank you! Worked well with test builds in 15.3.
