### ISSUE TITLE
Ability to include custom files to packaged app

### ISSUE THREAD

**Issue by galvanopus** [excelsior-oss/excelsior-jet-maven-plugin#17]
JetPackII allows to add custom (log4j.xml, config) files to a package. What about adding this to plugin? Might be I should use maven-resources-plugin for this?

**Comment by pjBooms** [comment]
Yes, it is possible to add it to the plugin. I am going to add the following parameter in the next micro-release of the plugin:

<customResources>resource-dir<customResources> with the default at "jetresources/packagefiles"

The contents of the dir will be copied to the final package than. 
You may use another Maven plugin to configure the contents of the directory.

Is it enough for your needs?

**Comment by dmitriyyavorskiy** [comment]
I have the same need. 
In my project there is a config folder and some dll's in the root folder. 
It would be very useful to have such an option to copy resources alongside the app and have them bundled into the installer package.

**Comment by galvanopus** [comment]
@pjBooms, yep, it would be enough. Thank you.

**Comment by dmitriyyavorskiy** [comment]
Thank you, Great, it works in 0.4.1. 
The only issue i still have it is a not copying resources to build folder, only to app. Test run is broken because of this.  
Great new feature for the plugin

**Comment by pjBooms** [comment]
I am waiting when it will be available on Maven Central before closing the issue...

Test Run copies resources to build folder, please check it.

**Comment by dmitriyyavorskiy** [comment]
It is actually on maven central. I have used it from there.

**Comment by pjBooms** [comment]
So please confirm or not that when you run 
```
jet:testrun
```
package files are copied to build folder as well (I have an integration test on this).

**Comment by pjBooms** [comment]
Fixed in 0.4.1 release with `<packageFilesDir>` plugin parameter

**Comment by galvanopus** [comment]
Confirmed.
