### ISSUE TITLE
Ability to create trial app

### ISSUE THREAD

**Issue by galvanopus** [excelsior-oss/excelsior-jet-maven-plugin#19]
I suppose this has already been included in backlog. Having this issue will help me to track it.

**Comment by pjBooms** [comment]
Yes, it is in backlog. But creating issues is a good way to prioritize appearance of new features. So do not hesitate to create them. 

BTW, new features is pretty easy to add by yourself via Pull Requests. Look, for instance,  this feature branch -- https://github.com/excelsior-oss/excelsior-jet-maven-plugin/tree/opt_rt_files that adds 'optRtFiles" parameter. It was implemented by @tfleis who is not our team member. Though particular this feature (trial apps), I am going to implement myself.

**Comment by pjBooms** [comment]
Fixed in 0.4.2 release

**Comment by galvanopus** [comment]
Thank you!
