### ISSUE TITLE
Ability to set system property

### ISSUE THREAD

**Issue by galvanopus** [excelsior-oss/excelsior-jet-maven-plugin#20]
For example, app is launched by
```
java -Dlog4j.defaultInitOverride=true -jar myapp.jar
```
I suggest there is a workaround in 0.4.1: using multi-app mode.

**Comment by pjBooms** [comment]
Thanx, the feature is scheduled for 0.4.3 release (will be released on the next week).

**Comment by pjBooms** [comment]
Fixed in 0.4.3 release

**Comment by galvanopus** [comment]
Thank you!
