### ISSUE TITLE
Service creation

### ISSUE THREAD

**Issue by dmitriyyavorskiy** [excelsior-oss/excelsior-jet-maven-plugin#25]
For some of my applications i need to create a service,so my app will start in the windows startup and run in background. 

It would be very useful to create such a service with maven plugin and even better if installer set it as a service.

**Comment by pjBooms** [comment]
You may use `<multiApp>` plugin parameter now as a workaround for service creation.

Windows Services are not supported in `xpack` command line now, so I cannot support them for the Excelsior Installer in the plugin. The next Excelsior JET version will support Windows Services in `xpack`, and I will support them in the plugin consequently.

**Comment by dmitriyyavorskiy** [comment]
Next version you mean 11.3 or 12 ?

**Comment by pjBooms** [comment]
11.3

**Comment by pjBooms** [comment]
Just released 0.9.0 version supports Windows services including Excelsior Installer packaging.
Please check and give feedback.

**Comment by dmitriyyavorskiy** [comment]
Cool. It is working good. 

Only problem i got and spend a lot of time is a working directory for the service. I my case it was set to c:\ and the service could not find a config folder. 
Fixed it by setting System.setProperty("user.dir", getWorkingDirectory());

**Comment by pjBooms** [comment]
Thanx, I am glad to see that it works for you.

Windows sets working directory for services by its own. 
Another common workaround to change it to the executable directory is adding the following JET VM options:

-Duser.dir=*{exe.dir} 
-Djet.cd.to.user.dir
