### ISSUE TITLE
Webkit not included

### ISSUE THREAD

**Issue by dmitriyyavorskiy** [excelsior-oss/excelsior-jet-maven-plugin#27]
I have built an application, it works fine, but when i open WebView panel, i got an error 

WARN 2016-03-26 11:26:27,665          SystemErr - Caused by: javafx.fxml.LoadException: 
unknown path:15

 WARN 2016-03-26 11:26:27,666          SystemErr - 	at javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
 WARN 2016-03-26 11:26:27,666          SystemErr - 	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
 WARN 2016-03-26 11:26:27,666          SystemErr - 	at javafx.fxml.FXMLLoader.load(Unknown Source)
 WARN 2016-03-26 11:26:27,666          SystemErr - 	... 49 more
 WARN 2016-03-26 11:26:27,666          SystemErr - Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 WARN 2016-03-26 11:26:27,667          SystemErr - 	at javafx.fxml.JavaFXBuilder$ObjectBuilder.build(Unknown Source)
 WARN 2016-03-26 11:26:27,667          SystemErr - 	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(Unknown Source)
 WARN 2016-03-26 11:26:27,667          SystemErr - 	at javafx.fxml.FXMLLoader.processEndElement(Unknown Source)
 WARN 2016-03-26 11:26:27,667          SystemErr - 	... 51 more
 WARN 2016-03-26 11:26:27,667          SystemErr - Caused by: java.lang.reflect.InvocationTargetException
 WARN 2016-03-26 11:26:27,667          SystemErr - 	at sun.reflect.misc.Trampoline.invoke(Unknown Source)
 WARN 2016-03-26 11:26:27,668          SystemErr - 	at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
 WARN 2016-03-26 11:26:27,668          SystemErr - 	... 54 more
 WARN 2016-03-26 11:26:27,668          SystemErr - Caused by: java.lang.NoClassDefFoundError: com.sun.webkit.WebPage
 WARN 2016-03-26 11:26:27,668          SystemErr - 	at javafx.scene.web.WebEngine.<init>(Unknown Source)
 WARN 2016-03-26 11:26:27,668          SystemErr - 	at javafx.scene.web.WebEngine.<init>(Unknown Source)
 WARN 2016-03-26 11:26:27,668          SystemErr - 	at javafx.scene.web.WebView.<init>(Unknown Source)
 WARN 2016-03-26 11:26:27,669          SystemErr - 	at javafx.scene.web.WebViewBuilder.build(Unknown Source)
 WARN 2016-03-26 11:26:27,669          SystemErr - 	... 56 more

I need manually add jfxwebkit.dll to the rt\bin folder to make it work.
I know this file is huge(39Mb) and usually not needed but i need it in my case. 
Can you add an option for such cases? 

Thanks

**Comment by pjBooms** [comment]
There is already option for this: https://github.com/excelsior-oss/excelsior-jet-maven-plugin/pull/8 .
You need to add the following plugin configuration for this:

                  <optRtFiles>
                    <param>javafx-webkit</param>
                  </optRtFiles>

Alternatively, it is enough to perform jet:testrun for your application where test your WebView functionality -- this way webkit will be included automatically. Next version of Excelsior ET includes webkit based on static import analyses.
