### ISSUE TITLE
Incompatibility with maven-jar-plugin in version >= 3.0.0

### ISSUE THREAD

**Issue by tfleis** [excelsior-oss/excelsior-jet-maven-plugin#44]
The build fails if you use the maven-jar-plugin with version >= 3.0.0:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.2:jar (default-jar) on project config-tool-jet: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]

I think that this is the cause:
https://issues.apache.org/jira/browse/MJAR-198

**Comment by pjBooms** [comment]
Please clarify in more details the problem. I have tried to add `maven-jar-plugin` to the list of plugins to a sample pom.xml:

```xml
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-jar-plugin</artifactId>
              <version>3.0.2</version>
          </plugin>
```

and it works ok with Excelsior JET Maven plugin.

**Comment by tfleis** [comment]
We have a separate pom.xml which only uses the excelsior-jet-maven-plugin to build another artifact (Maven module). It doesn't have source files. In this pom.xml we have to use packaging jar because this is only supported by your plugin. The maven-jar-plugin creates an empty jar for this Maven module.

The new maven-jar-plugin doesn't complain when I add the following configuration:
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <version>3.0.2</version>
 <configuration>
   <skipIfEmpty>true</skipIfEmpty>
  </configuration>
</plugin>
```
But your plugin complains about missing jar.

Do you have an idea?

**Comment by pjBooms** [comment]
Can you prepare an integration test at https://github.com/excelsior-oss/excelsior-jet-maven-plugin/tree/master/src/it that demonstrates the problem you have faced?

**Comment by pjBooms** [comment]
> We have a separate pom.xml which only uses the excelsior-jet-maven-plugin to build another artifact 
>(Maven module). 
Why do not you add the the excelsior-jet-maven-plugin only to that Maven module and do not add it to the  main pom.xml?

**Comment by pjBooms** [comment]
If you would provide more information about the issue, please let us know.

**Comment by tfleis** [comment]
All maven modules related to distribution of our application (AOT compilation, installer creation, ...) are located in a separate maven module which is enabled by a profile. We moved the AOT compilation to the maven module of the application now. You can keep this ticket closed.
