### ISSUE TITLE
Missing optional runtime components in documentation

### ISSUE THREAD

**Issue by liontiger23** [excelsior-oss/excelsior-jet-maven-plugin#47]
The documentation for [Optional Components](https://github.com/excelsior-oss/excelsior-jet-maven-plugin#optional-components) is missing some of the components: 

- JDK Tools
- JavaFX Bridge to Java2D/Swing
- JNDI DNS Provider
- Zip File System Provider

These components are present in JetPackII for Windows/x86.

BTW xpack's help lacks some of these components as well.

**Comment by pjBooms** [comment]
Fixed in 0.9.3 release
