### ISSUE TITLE
Support TYPICAL compilation mode (and use it by default)

### ISSUE THREAD

**Issue by liontiger23** [excelsior-oss/excelsior-jet-maven-plugin#48]
It seems that Excelsior JET plugin uses SMART compilation mode by default which does not compile all the dependencies ahead of time. This mode also requires Test Run to produce best results, but the essential data for SMART compilation is stored in .usg file which is not currently created on amd64 platforms.

So for better performance on average the default compilation mode should be TYPICAL, similarly to JetPackII. However, it would make sense to give user an option of choosing SMART mode as well.

**Comment by pjBooms** [comment]
Fixed in 0.9.4 release
