### ISSUE TITLE
Concern is setting allowDesktopInteraction works correctly 

### ISSUE THREAD

**Issue by dmitriyyavorskiy** [excelsior-oss/excelsior-jet-maven-plugin#56]
Hello, 
I have an issue with the service, built by the maven plugin, with the setting allowDesktopInteraction = true

Part of my pom.xml

```
<appType>windows-service</appType>
...
<windowsServiceConfiguration>
	<name>launcherservice</name>
	<displayName>Launcher service</displayName>
	<description>Launches all necessary apps</description>
	<allowDesktopInteraction>true</allowDesktopInteraction>
	<startupType>automatic</startupType>
	<startServiceAfterInstall>true</startServiceAfterInstall>
</windowsServiceConfiguration>
```

The purpose of the service is to listen to remote command and start apps on remote computers where it is installed.
Everything works fine, but I cannot see started apps. The service actually starts it, they are in the task manager, but i do not see them. 
If i build the app like a desktop app instead of a service i can see all my remotely launched apps.

There is the code in the service, responsible to remotely launch the desktop apps. 

```
DefaultExecutor executor = new DefaultExecutor();
CommandLine cmdLine = CommandLine.parse("D:\\test.exe");
executor.execute(cmdLine);
```

As far as i understand the setting allowDesktopInteraction should allow the service to start desktop apps.
Maybe something wrong with the setting or there is no possibility at all to start a desktop app from a service?

**Comment by pjBooms** [comment]
Hello, 

I believe this issue does not relate to the plugin so it is better to contact our support at java@excelsior-usa.com. 

 allowDesktopInteraction is very strange Windows service feature that creates an additional desktop for the service (so call session 0) where you can show some UI to a user.  The desktop can be shown by interactive services detection service -- it shows popup with prompting to see the desktop![image](https://cloud.githubusercontent.com/assets/2777612/23900883/7d7ea6b0-08ed-11e7-8ad6-51e747f6e3ba.png). 

According [this article](https://social.technet.microsoft.com/Forums/en-US/b4e29d63-3b66-4d63-be50-207aff7d6001/no-mouse-or-keyboard-access-in-session-0?forum=win10itprogeneral) there is an open bug in Windows 10: the desktop does not respond to user input so the feature is hardly usable now (and you need to patch registry to just start the interactive services detection service).

**Comment by dmitriyyavorskiy** [comment]
I got it, Thanks
