### ISSUE TITLE
Dependency type pom causes build error with JetPackII

### ISSUE THREAD

**Issue by andrebbc** [excelsior-oss/excelsior-jet-maven-plugin#70]
After adding a dependency with <type>pom</type>, excelsior-jet build failed during JetPackII phase:

[INFO] Application terminated with exit code 0
[INFO] Profile successfully hard-wired into <....>
[INFO] JetPackII batch mode
[INFO] Fatal error: This project contains unresolved resource items and cannot be processed. The list of unresolved items: 

Workaround is to move pom dependency to <dependencyManagement> and set <scope>import</scope>

**Comment by pjBooms** [comment]
Thank you for the bug report!
It's fixed in 1.1,3 release. Please confirm
