### ISSUE TITLE
Plugin ignores pom profiles; Last defined is always used

### ISSUE THREAD

**Issue by fhoess** [excelsior-oss/excelsior-jet-maven-plugin#72]
I use Jenkins for continously building and testing our software.
For this it is required to first build the software (with -jet:build, -jet:profile is not possible) without PGO. Then I start automated profiling. After that I want to run a second build with activated PGO.

For this, I define two profiles in my pom file. One with PGO and one without PGO. Put when I run the build only the last defined profile is used.

Is it possible to run 2 diffrent configurations within one pom file, without commiting changes to the code repository?

**Comment by pjBooms** [comment]
AFAIK, profile changing is controlled by "-P <profile>" Maven command line switch (http://maven.apache.org/guides/introduction/introduction-to-profiles.html).

Does it answer your question?

**Comment by pjBooms** [comment]
Please also describe why just "jet:profile" does not work for you and how you enable PGO then.
In other words, we need more information about your problem.

**Comment by fhoess** [comment]
Ok thank you. To clarify this: Yes, I use different plugin configurations. 

In the first run I use: -P PGO_false jet:build
and in the second: -P PGO_true jet:build
with the following scheme in pom.xml:
  ```
...
  <profiles>
      <profile>
        <id>PGO_false</id>
       ...
       <build>
	  <plugins>
	     <plugin>
		<groupId>com.excelsiorjet</groupId>		
        ...
<!-- PGO is not used -->
<!-- <compilerOption>-pgo+</compilerOption> -->
<!-- <compilerOption>-jprofile=F:\path\app.jprof</compilerOption> -->
<!-- <compilerOption>-global+</compilerOption> -->
...
	      </plugin>
	   </plugins>
	</build>
        ...
      </profile>

<profile>
        <id>PGO_true</id>
       ...
       <build>
	  <plugins>
	     <plugin>
		<groupId>com.excelsiorjet</groupId>		
...
<!-- PGO is used -->
<compilerOption>-pgo+</compilerOption>
<compilerOption>-jprofile=F:\path\app.jprof</compilerOption>
<compilerOption>-global+</compilerOption>
        ...
	      </plugin>
	   </plugins>
	</build>
        ...
      </profile>
    </profiles>
...
```

The first run with "-P PGO_false jet:build" produces a build with the PGO_true profile.


After compilation (and packing) of the first run I use some batch scripts to deploy and run the application on target system. e.g. "app.exe -Djet.profiler". Then some automated tests are running to gather the app.jprof file. But the JET-PGO-Profiler crashes regularly with our App on server and laptop systems. Desktop systems seems to work better. So the target system can change. This is the reason why I need a full functional build as a workaround, which I can deploy on different systems/hardware. Thats why I use jet:build instead of jet:profile. (Btw: I already sent a ticket for this issue).

Thanks in advance. :)

**Comment by pjBooms** [comment]
It seems you missed `<compilerOptions></compilerOptions>` braces around set of `<compilerOption>` settings, so they were ignored by the plugin (unfortunately Maven does not warn if you set unknown plugin properties). I tried your sample with the braces and it works ok for me.

For your case, I can also suggest to use jet:profile with 
```'xml
<execProfiles>
   <profileLocally>false</profileLocally>
</execProfiles>
```
configuration. 
In this case, the plugin will create just a profiling image without actually running it (and a zip file with the image). 
Then you can deploy the image to target systems, run the executable and the profile will be collected (without need to specify  -Djet.profiler property manually).
Then you may copy the profile to `src/main/jetresources` (you can configure the profile placement as well) and  `jet:build` will automatically pick it up and enable PGO.
In this case, you won't need to have two different Maven profiles. Please let me know if this scenario does not fit you and why. 
For more information, please read https://github.com/excelsior-oss/excelsior-jet-maven-plugin/wiki/Build-Process#execution-profiles-configuration-parameters
