### ISSUE TITLE
Do not fork own maven lifecycle

### ISSUE THREAD

**Issue by lbeuster** [excelsior-oss/excelsior-jet-maven-plugin#82]
Currently the plugin (at least the BuildMojo) forks it own maven lifecycle (package). This makes it hard to use the plugin in multi projects and integrate it into the regular lifecycle (see also #81)

Removing the @Execute annotation at class level would solve the problem. But then it's not backward compatible anymore. Executing a "mvn jet:build" was enough to build the complete project. With the change you would have to integrate the plugin into the pom.xml and call a "mvn package" - but that's the maven way.

However the fix would look like, all other mojos should get the same fix.

**Comment by pjBooms** [comment]
To keep the plugin backward compatible, I think to create parallel goals with "jet-" prefix that do not fork Maven execution for using them inside `<goal>` maven declarations. Is it ok for you?

**Comment by lbeuster** [comment]
Yes, ok for me.

**Comment by pjBooms** [comment]
Fixed in 1.3.2 release where `jet-build`, `jet-testrun`, `jet-profile` goals introduced that do not fork Maven lifecycle and thus can be used inside Maven `<executions><execution><goals><goal>` declarations.
Please check if it works for you.

**Comment by lbeuster** [comment]
Thanks, works.

The only limitation is that the plugin needs the packaged jar for a jet-testrun (maybe also for jet-build). Normally the compiled classed in target/classes should be enough. This did not came up before because the plugin always executed the phase package before the build.
No problem for me but unexpected.

Can be tested with
```
# works, because jar-plugin runs in phase "package"
mvn clean package jet:jet-testrun

# doesn't work with error from jet-plugin: Jar ... was not found...
mvn clean prepare-package jet:jet-testrun
```

**Comment by pjBooms** [comment]
> Normally the compiled classed in target/classes should be enough

It can be enough but actually the environment differs when you execute an application with a jar or with plain classes. So such a run does not fully emulate resulting run and it can be essential. So we prefer to perform Test Run on final artifacts.

>The only limitation is that the plugin needs the packaged jar for a jet-testrun (maybe also for jet-build

Just use old `jet:testrun` for that on the command line. New goals are intended for using within `<goal>` Maven declarations only.
