### ISSUE TITLE
Missing option for adding "tools.jar" to package

### ISSUE THREAD

**Issue by tfleis** [excelsior-oss/excelsior-jet-maven-plugin#9]
We have several applications which are compiled by Excelsior JET. Some of them need "tools.jar" at runtime. At the moment we just copy "tools.jar" to the lib directory of the Java profile of Excelsior JET. Unfortunately all applications will contain this file although not all need it. We need an option in the maven plugin to configure whether the tools.jar should be embedded or not.

**Comment by pjBooms** [comment]
Please clarify how you would like for tools.jar to be added:

1. As a part of the target executable classpath. This way, we can add tools.jar to dependencies of the executable like other dependencies and it will be compiled into the executable (and will be available at runtime as other dependencies via application classpath). However tools.jar will not be present as a separate file in the resulting package.

2. You need tools.jar to be present as a separate file in the resulting package. It will not be added to the application classpath of the target executable. If it is so, please let us know how do you access the jar from the application? Is it required for it to be in "rt/lib" folder (if yes, why) or it is enough to place it to the root of the package (near to the executable)?

**Comment by tfleis** [comment]
1. As far as I know since Java 7 it is not possible anymore to add tools.jar to classpath (see e.g. http://vyazelenko.com/2012/07/05/where-to-put-tools-jar-in-jre-7/). We also do not want to compile tools.jar with every build. It takes quite a long time. 

2. We have copied "tools.jar" from "C:\Program Files\jet11.0-pro-amd64\profile1.8.0_65\lib" to "C:\Program Files\jet11.0-pro-amd64\profile1.8.0_65\jre\lib". When we compile an application  "tools.jar" is automatically saved to "rt\lib" of the resulting zip file by Excelsior JET.

We need tools.jar for compiling java source code at runtime. We just call "javax.tools.ToolProvider.getSystemJavaCompiler()". The return value is null when tools.jar is missing.

**Comment by pjBooms** [comment]
Yes, you are right. This issue cannot be fixed in a good way in the scope of the plugin: 
tools.jar must be an optional JET Runtime component that should be supported by Excelsior JET itself.

Right now, I can only automate your workaround adding tools.jar to the pofileXXX/jre/lib before packaging and removing it afterwards.

**Comment by pjBooms** [comment]
"tools.jar" will be supported as optional RT component in the next version of Excelsior JET (scheduled for May). Maven plugin will also support it automatically after the new Excelsior JET release.

**Comment by tfleis** [comment]
Glad to hear that. We are looking forward to that feature.

**Comment by pjBooms** [comment]
Excelsior JET 11.3 released with this feature supported
